import React, { useState, useEffect } from 'react';
import api from '../../api/axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { FileText, Download, Loader, Filter, Award, BarChart3, TrendingUp } from 'lucide-react';

const MONTHS = [
    { value: 1, label: 'January', short: 'Jan' },
    { value: 2, label: 'February', short: 'Feb' },
    { value: 3, label: 'March', short: 'Mar' },
    { value: 4, label: 'April', short: 'Apr' },
    { value: 5, label: 'May', short: 'May' },
    { value: 6, label: 'June', short: 'Jun' },
    { value: 7, label: 'July', short: 'Jul' },
    { value: 8, label: 'August', short: 'Aug' },
    { value: 9, label: 'September', short: 'Sep' },
    { value: 10, label: 'October', short: 'Oct' },
    { value: 11, label: 'November', short: 'Nov' },
    { value: 12, label: 'December', short: 'Dec' }
];

const COMPANY_TARGETS = {
    'Total New Orders': 50,
    'Net Profit': 10000,
    'Average Order Value': 500,
    'Return on Investment (ROI)': 120,
    'Order Completion Rate': 95,
    'On-Time Delivery Rate': 98,
    'Cancellation Rate': 2,
    'Average Response Time': 2,
    'Customer Satisfaction Score': 4.5,
    'Repeat Customer Rate': 30,
    'Quality of Work Product': 5,
    'Dispute Rate': 1,
    'Disputes Converted to Satisfied': 5,
    'Tips or Recognition': 100,
    'Adaptability & Learning': 5
};

const LOWER_IS_BETTER = new Set(['Cancellation Rate', 'Average Response Time', 'Dispute Rate']);

const getMonthName = (monthNum) => MONTHS.find(month => month.value === parseInt(monthNum))?.label || 'All Months';
const getPeriodLabel = (year, month) => month === 'all' ? `All Months ${year}` : `${getMonthName(month)} ${year}`;
const formatCurrency = (value) => `LKR ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const formatNumber = (value) => Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 2 });
const formatPercent = (value) => `${Number(value || 0).toFixed(1)}%`;

const getCompanyScore = (name, value) => {
    const target = COMPANY_TARGETS[name];
    if (!target || value === undefined || value === null) return null;
    const safeValue = Math.max(Number(value), 0.01);
    const rawScore = LOWER_IS_BETTER.has(name) ? (target / safeValue) * 100 : (Number(value) / target) * 100;
    return Math.min(rawScore, 100);
};

const getSelectedPeriods = (year, month) => {
    if (month !== 'all') return [`${year}-${String(month).padStart(2, '0')}`];
    return MONTHS.map(item => `${year}-${String(item.value).padStart(2, '0')}`);
};

const drawReportHeader = (doc, title, subtitle) => {
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text(title, 14, 14);
    doc.setFontSize(10);
    doc.text(subtitle, 14, 23);
    doc.setTextColor(31, 41, 55);
};

const addFooter = (doc) => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(107, 114, 128);
        doc.text(`Generated by TechZnap EPMS | Page ${i} of ${pageCount}`, 14, 288);
    }
    doc.setTextColor(31, 41, 55);
};

const getLastTableY = (doc, fallback = 45) => doc.lastAutoTable?.finalY ? doc.lastAutoTable.finalY + 8 : fallback;

const Reports = () => {
    const [loadingReport, setLoadingReport] = useState('');
    const [employees, setEmployees] = useState([]);

    const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
    const [selectedMonth, setSelectedMonth] = useState(new Date().getMonth() + 1);
    const [selectedEmployee, setSelectedEmployee] = useState('all');

    useEffect(() => {
        fetchEmployees();
    }, []);

    const fetchEmployees = async () => {
        try {
            const res = await api.get('/staff');
            setEmployees(res.data);
        } catch (error) {
            console.error('Error fetching staff:', error);
        }
    };

    const filterByEmployee = (employeeId) => selectedEmployee === 'all' || Number(employeeId) === Number(selectedEmployee);

    const generateBonusReport = async () => {
        setLoadingReport('bonus');
        try {
            const response = await api.get('/bonuses');
            const bonuses = response.data.filter(b => {
                if (!b.employee) return false;
                const bonusDate = new Date(b.dateGiven);
                const matchYear = bonusDate.getFullYear() === parseInt(selectedYear);
                const matchMonth = selectedMonth === 'all' || (bonusDate.getMonth() + 1) === parseInt(selectedMonth);
                return matchYear && matchMonth && filterByEmployee(b.employeeId);
            });

            if (bonuses.length === 0) {
                alert('No bonus records found for the selected criteria.');
                return;
            }

            const totalAmount = bonuses.reduce((sum, bonus) => sum + Number(bonus.amount || 0), 0);
            const averageAmount = totalAmount / bonuses.length;
            const byEmployee = Object.values(bonuses.reduce((acc, bonus) => {
                const key = bonus.employeeId;
                acc[key] = acc[key] || { employee: bonus.employee.username, count: 0, amount: 0 };
                acc[key].count += 1;
                acc[key].amount += Number(bonus.amount || 0);
                return acc;
            }, {})).sort((a, b) => b.amount - a.amount);
            const byReason = Object.values(bonuses.reduce((acc, bonus) => {
                const key = bonus.reason || 'Not specified';
                acc[key] = acc[key] || { reason: key, count: 0, amount: 0 };
                acc[key].count += 1;
                acc[key].amount += Number(bonus.amount || 0);
                return acc;
            }, {})).sort((a, b) => b.amount - a.amount);

            const doc = new jsPDF();
            drawReportHeader(doc, 'Bonus History Report', `Period: ${getPeriodLabel(selectedYear, selectedMonth)} | Generated: ${new Date().toLocaleDateString()}`);

            autoTable(doc, {
                startY: 40,
                head: [['Summary Metric', 'Value']],
                body: [
                    ['Bonus Records', bonuses.length],
                    ['Total Bonus Amount', formatCurrency(totalAmount)],
                    ['Average Bonus Amount', formatCurrency(averageAmount)],
                    ['Top Employee by Bonus', byEmployee[0] ? `${byEmployee[0].employee} (${formatCurrency(byEmployee[0].amount)})` : '-'],
                    ['Top Bonus Reason', byReason[0] ? `${byReason[0].reason} (${formatCurrency(byReason[0].amount)})` : '-']
                ],
                theme: 'grid',
                headStyles: { fillColor: [37, 99, 235] }
            });

            autoTable(doc, {
                startY: getLastTableY(doc),
                head: [['Employee', 'Count', 'Total Amount']],
                body: byEmployee.map(row => [row.employee, row.count, formatCurrency(row.amount)]),
                theme: 'striped',
                headStyles: { fillColor: [22, 163, 74] }
            });

            autoTable(doc, {
                startY: getLastTableY(doc),
                head: [['Date', 'Employee', 'Reason', 'Amount']],
                body: bonuses.map(b => [
                    new Date(b.dateGiven).toLocaleDateString(),
                    b.employee.username,
                    b.reason || '-',
                    formatCurrency(b.amount)
                ]),
                theme: 'grid',
                headStyles: { fillColor: [55, 65, 81] },
                styles: { fontSize: 9 }
            });

            addFooter(doc);
            doc.save(`bonus_report_${selectedYear}_${selectedMonth}.pdf`);
        } catch (error) {
            console.error('Report Generation Error', error);
            alert('Failed to generate Bonus Report.');
        } finally {
            setLoadingReport('');
        }
    };

    const generatePerformanceReport = async () => {
        setLoadingReport('performance');
        try {
            const response = await api.get('/evaluations');
            const evaluations = response.data.filter(e => {
                if (!e.employee || !e.period) return false;
                const [eYear, eMonth] = e.period.split('-');
                const matchYear = parseInt(eYear) === parseInt(selectedYear);
                const matchMonth = selectedMonth === 'all' || parseInt(eMonth) === parseInt(selectedMonth);
                return matchYear && matchMonth && filterByEmployee(e.employeeId);
            });

            if (evaluations.length === 0) {
                alert('No evaluations found for the selected criteria.');
                return;
            }

            const detailedEvaluations = await Promise.all(
                evaluations.map(async (evaluation) => {
                    const detailsRes = await api.get(`/evaluations/${evaluation.id}`);
                    const details = detailsRes.data.details || [];
                    const averageRating = details.length
                        ? details.reduce((sum, item) => sum + Number(item.rating || 0), 0) / details.length
                        : 0;
                    return { ...evaluation, details, averageRating, score: (averageRating / 5) * 100 };
                })
            );

            const avgScore = detailedEvaluations.reduce((sum, item) => sum + item.score, 0) / detailedEvaluations.length;
            const uniqueEmployees = new Set(detailedEvaluations.map(item => item.employeeId)).size;
            const byType = Object.values(detailedEvaluations.reduce((acc, evaluation) => {
                acc[evaluation.type] = acc[evaluation.type] || { type: evaluation.type, count: 0, avgScore: 0 };
                acc[evaluation.type].count += 1;
                acc[evaluation.type].avgScore += evaluation.score;
                return acc;
            }, {})).map(item => ({ ...item, avgScore: item.avgScore / item.count }));

            const criterionRows = detailedEvaluations.flatMap(evaluation => evaluation.details.map(detail => [
                evaluation.employee.username,
                evaluation.type,
                detail.kpi?.title || 'KPI',
                `${detail.rating}/5`,
                detail.comment || '-'
            ]));

            const doc = new jsPDF();
            drawReportHeader(doc, 'Performance Evaluation Report', `Period: ${getPeriodLabel(selectedYear, selectedMonth)} | Generated: ${new Date().toLocaleDateString()}`);

            autoTable(doc, {
                startY: 40,
                head: [['Summary Metric', 'Value']],
                body: [
                    ['Evaluation Records', detailedEvaluations.length],
                    ['Employees Covered', uniqueEmployees],
                    ['Average Rating', `${(avgScore / 20).toFixed(1)} / 5.0`],
                    ['Average Score', formatPercent(avgScore)]
                ],
                theme: 'grid',
                headStyles: { fillColor: [37, 99, 235] }
            });

            autoTable(doc, {
                startY: getLastTableY(doc),
                head: [['Type', 'Count', 'Average Score']],
                body: byType.map(item => [item.type, item.count, formatPercent(item.avgScore)]),
                theme: 'striped',
                headStyles: { fillColor: [22, 163, 74] }
            });

            autoTable(doc, {
                startY: getLastTableY(doc),
                head: [['Employee', 'Type', 'Period', 'Evaluator', 'Rating', 'Score', 'Comments']],
                body: detailedEvaluations.map(e => [
                    e.employee.username,
                    e.type,
                    e.period,
                    e.evaluator ? e.evaluator.username : 'Self',
                    `${e.averageRating.toFixed(1)} / 5`,
                    formatPercent(e.score),
                    e.comments || '-'
                ]),
                theme: 'grid',
                headStyles: { fillColor: [55, 65, 81] },
                styles: { fontSize: 8 },
                columnStyles: { 6: { cellWidth: 45 } }
            });

            if (criterionRows.length > 0) {
                autoTable(doc, {
                    startY: getLastTableY(doc),
                    head: [['Employee', 'Type', 'Criterion', 'Rating', 'Comment']],
                    body: criterionRows,
                    theme: 'striped',
                    headStyles: { fillColor: [79, 70, 229] },
                    styles: { fontSize: 8 },
                    columnStyles: { 2: { cellWidth: 55 }, 4: { cellWidth: 45 } }
                });
            }

            addFooter(doc);
            doc.save(`performance_report_${selectedYear}_${selectedMonth}.pdf`);
        } catch (error) {
            console.error('Report Generation Error', error);
            alert('Failed to generate Performance Report.');
        } finally {
            setLoadingReport('');
        }
    };

    const generateCompanyReport = async () => {
        setLoadingReport('company');
        try {
            const periods = getSelectedPeriods(selectedYear, selectedMonth);
            const [metricsRes, ...logResponses] = await Promise.all([
                api.get('/company-data/metrics'),
                ...periods.map(period => api.get(`/company-data/logs?period=${period}`))
            ]);

            const logsByPeriod = {};
            periods.forEach((period, index) => {
                logsByPeriod[period] = logResponses[index].data;
            });

            const metricRows = metricsRes.data.map(metric => {
                const values = periods.map(period => {
                    const log = logsByPeriod[period].find(item => item.metricId === metric.id);
                    const value = log ? Number(log.value) : null;
                    return { period, value, score: value !== null ? getCompanyScore(metric.name, value) : null };
                });
                const validScores = values.filter(item => item.score !== null);
                const latest = [...values].reverse().find(item => item.value !== null);
                return {
                    name: metric.name,
                    unit: metric.unit || '',
                    target: COMPANY_TARGETS[metric.name],
                    latestValue: latest?.value ?? null,
                    latestPeriod: latest?.period || '-',
                    avgScore: validScores.length ? validScores.reduce((sum, item) => sum + item.score, 0) / validScores.length : null,
                    values
                };
            }).filter(row => row.values.some(item => item.value !== null));

            if (metricRows.length === 0) {
                alert('No company data found for the selected criteria.');
                return;
            }

            const scoredRows = metricRows.filter(row => row.avgScore !== null);
            const averagePerformance = scoredRows.length
                ? scoredRows.reduce((sum, row) => sum + row.avgScore, 0) / scoredRows.length
                : 0;
            const lowPerformers = [...scoredRows].sort((a, b) => a.avgScore - b.avgScore).slice(0, 5);

            const doc = new jsPDF();
            drawReportHeader(doc, 'Company Performance Report', `Period: ${getPeriodLabel(selectedYear, selectedMonth)} | Generated: ${new Date().toLocaleDateString()}`);

            autoTable(doc, {
                startY: 40,
                head: [['Summary Metric', 'Value']],
                body: [
                    ['Tracked Metrics with Data', metricRows.length],
                    ['Average Target Achievement', formatPercent(averagePerformance)],
                    ['Lowest Performing Metric', lowPerformers[0] ? `${lowPerformers[0].name} (${formatPercent(lowPerformers[0].avgScore)})` : '-'],
                    ['Reporting Periods', periods.join(', ')]
                ],
                theme: 'grid',
                headStyles: { fillColor: [37, 99, 235] }
            });

            autoTable(doc, {
                startY: getLastTableY(doc),
                head: [['Metric', 'Target', 'Latest Period', 'Latest Value', 'Avg Achievement']],
                body: metricRows.map(row => [
                    row.name,
                    row.target ? `${formatNumber(row.target)} ${row.unit}` : '-',
                    row.latestPeriod,
                    row.latestValue !== null ? `${formatNumber(row.latestValue)} ${row.unit}` : '-',
                    row.avgScore !== null ? formatPercent(row.avgScore) : '-'
                ]),
                theme: 'grid',
                headStyles: { fillColor: [22, 163, 74] },
                styles: { fontSize: 8 }
            });

            autoTable(doc, {
                startY: getLastTableY(doc),
                head: [['Attention Area', 'Average Achievement']],
                body: lowPerformers.map(row => [row.name, formatPercent(row.avgScore)]),
                theme: 'striped',
                headStyles: { fillColor: [220, 38, 38] }
            });

            addFooter(doc);
            doc.save(`company_performance_report_${selectedYear}_${selectedMonth}.pdf`);
        } catch (error) {
            console.error('Report Generation Error', error);
            alert('Failed to generate Company Performance Report.');
        } finally {
            setLoadingReport('');
        }
    };

    const reportCards = [
        {
            id: 'performance',
            title: 'Performance Evaluation Report',
            description: 'Includes average score, evaluation type breakdown, comments, and criterion-level ratings.',
            icon: BarChart3,
            color: 'bg-green-600 hover:bg-green-700',
            onClick: generatePerformanceReport
        },
        {
            id: 'bonus',
            title: 'Bonus History Report',
            description: 'Includes bonus totals, averages, top employees, reason breakdown, and detailed payments.',
            icon: Award,
            color: 'bg-blue-600 hover:bg-blue-700',
            onClick: generateBonusReport
        },
        {
            id: 'company',
            title: 'Company Performance Report',
            description: 'Uses Company Data entries to summarize target achievement and weak performance areas.',
            icon: TrendingUp,
            color: 'bg-indigo-600 hover:bg-indigo-700',
            onClick: generateCompanyReport
        }
    ];

    return (
        <div className="p-6 bg-gray-50 min-h-screen">
            <div className="mb-6">
                <h2 className="text-2xl font-bold text-gray-800 flex items-center">
                    <FileText className="mr-2 text-blue-600" />
                    System Reports
                </h2>
                <p className="text-sm text-gray-500 mt-1">Generate PDF reports with summary analysis, detailed records, and clear management insights.</p>
            </div>

            <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200 mb-6 flex flex-wrap gap-4 items-end">
                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Year</label>
                    <select
                        value={selectedYear}
                        onChange={(e) => setSelectedYear(e.target.value)}
                        className="block w-32 pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-md border"
                    >
                        <option value="2025">2025</option>
                        <option value="2026">2026</option>
                        <option value="2027">2027</option>
                    </select>
                </div>

                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Month</label>
                    <select
                        value={selectedMonth}
                        onChange={(e) => setSelectedMonth(e.target.value)}
                        className="block w-40 pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-md border"
                    >
                        <option value="all">All Months</option>
                        {MONTHS.map(month => (
                            <option key={month.value} value={month.value}>{month.label}</option>
                        ))}
                    </select>
                </div>

                <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Employee</label>
                    <select
                        value={selectedEmployee}
                        onChange={(e) => setSelectedEmployee(e.target.value)}
                        className="block w-64 pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-md border"
                    >
                        <option value="all">All Employees</option>
                        {employees
                            .filter(emp => emp.role === 'Employee')
                            .map(emp => (
                                <option key={emp.id} value={emp.id}>{emp.username} ({emp.email})</option>
                            ))}
                    </select>
                </div>

                <div className="pb-2 text-sm text-gray-500 flex items-center">
                    <Filter className="w-4 h-4 mr-1" />
                    Filters apply before PDF generation
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {reportCards.map((report) => {
                    const Icon = report.icon;
                    const isLoading = loadingReport === report.id;
                    return (
                        <div key={report.id} className="bg-white p-6 rounded-lg shadow-md border border-gray-200 flex flex-col">
                            <div className="w-12 h-12 rounded-lg bg-gray-100 flex items-center justify-center mb-4">
                                <Icon className="w-6 h-6 text-gray-700" />
                            </div>
                            <h3 className="text-lg font-semibold text-gray-800 mb-2">{report.title}</h3>
                            <p className="text-sm text-gray-500 mb-6 flex-1">{report.description}</p>
                            <button
                                onClick={report.onClick}
                                disabled={Boolean(loadingReport)}
                                className={`w-full flex items-center justify-center text-white font-medium py-2 px-4 rounded transition-colors disabled:bg-gray-400 ${report.color}`}
                            >
                                {isLoading ? <Loader className="animate-spin mr-2 h-5 w-5" /> : <Download className="mr-2 h-5 w-5" />}
                                {isLoading ? 'Generating...' : 'Download PDF'}
                            </button>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

export default Reports;
